version: "3"
services:
  test:
    image: "golang:1.16"
    volumes:
      - .:/search-movies
    working_dir: /search-movies
    command: /bin/true
    depends_on:
      - postgres
    environment:
      SERVER_HTTP_PORT: 8085
      SERVER_GRPC_PORT: 9080
      OMDB_KEY: faf7e5bb
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: go
      DB_USERNAME: go
      DB_PASSWORD: mypassword
      DB_SSL_ENABLED: "false"
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=go
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=go